os:
- osx
- linux

osx_image: xcode10.1
language: java
jdk: openjdk8
dist: xenial

addons:
  apt:
    packages:
    - python
    - python-requests
    - openjdk-8-jdk
    - build-essential
    - automake
    - libtool
    - gcc-arm-linux-gnueabi
    - libc6-dev-armel-cross
  homebrew:
    taps: homebrew/cask-versions
    casks:
      - java8
    packages:
      - python@2


before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip2 install requests; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(echo /Library/Java/JavaVirtualMachines/jdk1.8.0_*.jdk/Contents/Home);
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/;
  fi
- echo $JAVA_HOME

install:
- ./gradlew assemble
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd native && ./BUILD.sh && cd ..; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd native && ./BUILD.sh && cd ..; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd native && ./BUILD.sh --target=arm-linux-gnueabi --host=arm-linux-gnueabi && cd ..; fi
- ./gradlew buildWithNative # also copies files into build-native

script:
- ./gradlew check
- find build-native

deploy:
  - provider: releases
    api_key:
      secure: JwlNEGSjr6KFXSax24WA31XZdPlk1XMSFP8jDM+0lAtUvFRi2yw865KBEDJ2JFEAGskHze/0wL4fteyVsmG3LbWg6afsV6gFrpZCEIRHfGlYECbJTBao56cbxG31FlcrGKdehdR/0UTO6cbPzQj0I8atdY5GtILQK31d57sh4j7SkgtNdSGCa7Olg6Xil59RnrdJn9k4+cQiF4XeCgjsLg3bSnjczmjQIg1HPfpdWO6pQGXW219mdPBKfhTjs9bgejBkO+WW0L65rPcpZpvpAGdhCtDU8tX8RLwhd8YKmhx0KuGPJvRuaEwnYXzXMaiUyBNsuXjZxDoDEPGFctXBrj8i/Cz2g7uzam2oioWjr4d5qzej1O6aZC/GX2kPwIZLOTUvjE8D1L1GwHHVadunLo5jMFS5lROhQmtHC8RXtVjE+8uc7G5pkrOJ5Ic7ymnIpMd/Hv9neMO1a/b29Mq6kIsmbK/V2CUH2y41gG3Y4Njuc90Qv4EoZhYbjHJXAuhYRecXjJd5L0/oYnz5iSNrvlxfT/UdYggWTivetZl2XHQV2EWce8L+Ta71l0em+UPOv4ueJcETitLQw7WHoHKu7k/VCN5RgCUCrg5BZEd+7q1IDyS/IkM+mdxnlMrsl3iFNcg0hmV+5+UWyQBFuKjW8XqvyZYb+6lGuvUzZtw1iyo=
    skip_cleanup: true
    overwrite: true
    file_glob: true
    file:
      - build-native/*
    on:
      tags: true
      
  ## wait some (for osx to finish building), then download native libs and deploy
  - provider: script
    api_key:
      secure: JwlNEGSjr6KFXSax24WA31XZdPlk1XMSFP8jDM+0lAtUvFRi2yw865KBEDJ2JFEAGskHze/0wL4fteyVsmG3LbWg6afsV6gFrpZCEIRHfGlYECbJTBao56cbxG31FlcrGKdehdR/0UTO6cbPzQj0I8atdY5GtILQK31d57sh4j7SkgtNdSGCa7Olg6Xil59RnrdJn9k4+cQiF4XeCgjsLg3bSnjczmjQIg1HPfpdWO6pQGXW219mdPBKfhTjs9bgejBkO+WW0L65rPcpZpvpAGdhCtDU8tX8RLwhd8YKmhx0KuGPJvRuaEwnYXzXMaiUyBNsuXjZxDoDEPGFctXBrj8i/Cz2g7uzam2oioWjr4d5qzej1O6aZC/GX2kPwIZLOTUvjE8D1L1GwHHVadunLo5jMFS5lROhQmtHC8RXtVjE+8uc7G5pkrOJ5Ic7ymnIpMd/Hv9neMO1a/b29Mq6kIsmbK/V2CUH2y41gG3Y4Njuc90Qv4EoZhYbjHJXAuhYRecXjJd5L0/oYnz5iSNrvlxfT/UdYggWTivetZl2XHQV2EWce8L+Ta71l0em+UPOv4ueJcETitLQw7WHoHKu7k/VCN5RgCUCrg5BZEd+7q1IDyS/IkM+mdxnlMrsl3iFNcg0hmV+5+UWyQBFuKjW8XqvyZYb+6lGuvUzZtw1iyo=
    skip_cleanup: true
    script: sleep 300 && ./download-native-libs.py && ./gradlew buildWithNative
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME != osx"
  - provider: releases
    api_key:
      secure: JwlNEGSjr6KFXSax24WA31XZdPlk1XMSFP8jDM+0lAtUvFRi2yw865KBEDJ2JFEAGskHze/0wL4fteyVsmG3LbWg6afsV6gFrpZCEIRHfGlYECbJTBao56cbxG31FlcrGKdehdR/0UTO6cbPzQj0I8atdY5GtILQK31d57sh4j7SkgtNdSGCa7Olg6Xil59RnrdJn9k4+cQiF4XeCgjsLg3bSnjczmjQIg1HPfpdWO6pQGXW219mdPBKfhTjs9bgejBkO+WW0L65rPcpZpvpAGdhCtDU8tX8RLwhd8YKmhx0KuGPJvRuaEwnYXzXMaiUyBNsuXjZxDoDEPGFctXBrj8i/Cz2g7uzam2oioWjr4d5qzej1O6aZC/GX2kPwIZLOTUvjE8D1L1GwHHVadunLo5jMFS5lROhQmtHC8RXtVjE+8uc7G5pkrOJ5Ic7ymnIpMd/Hv9neMO1a/b29Mq6kIsmbK/V2CUH2y41gG3Y4Njuc90Qv4EoZhYbjHJXAuhYRecXjJd5L0/oYnz5iSNrvlxfT/UdYggWTivetZl2XHQV2EWce8L+Ta71l0em+UPOv4ueJcETitLQw7WHoHKu7k/VCN5RgCUCrg5BZEd+7q1IDyS/IkM+mdxnlMrsl3iFNcg0hmV+5+UWyQBFuKjW8XqvyZYb+6lGuvUzZtw1iyo=
    skip_cleanup: true
    overwrite: true
    file_glob: true
    file:
    - build/libs-all/*.jar
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME != osx"
